export type CellData = {
  x: number;
  y: number;
  i: number;
  uid?: number;
  bid?: string;
  n?: string;
  tid?: number;
  l?: number;
  pl?: number;
  r?: number;
  dm?: number;
  lo?: number;
  fr?: number;
  p?: number;
  d?: number;
  t?: number;
  b?: number;
  rel?: number;
  fbid?: string | null | undefined;
  pic_square?: string | null | undefined;
};
