#!/usr/bin/env bash
#
# Build the iOS .ipa for BYM Refitted (prod / multiplayer server).
#
# WHAT THIS DOES
#   1. Compiles the game SWF prod-pointed (https://server.bymrefitted.com) via asconfigc.
#   2. Copies it next to the iOS AIR descriptor.
#   3. Packages an .ipa with adt (Harman AIR SDK) in interpreter mode.
#
# WHAT IT DOES NOT DO
#   - It does not install on your iPhone (use Sideloadly / AltStore for that).
#   - It does not solve touch/fullscreen scaling (that is the CONFIG::MOBILE work
#     in GAME.as — Phase B — see ios/README.md).
#
# ⚠️  UNTESTED: this script was written without the AIR SDK or a device present.
#     Treat the exact adt/asconfigc flags as a strong starting point, not gospel.
#
# REQUIREMENTS (install once — see ios/README.md):
#   - Harman AIR SDK          -> export AIR_SDK_HOME=/path/to/AIRSDK
#   - asconfigc               -> npm i -g asconfigc
#   - A free Apple dev cert + provisioning profile (from Xcode free provisioning
#     or generated by Sideloadly). Only needed to satisfy adt's packaging.
#
# USAGE
#   export AIR_SDK_HOME=/path/to/AIRSDK
#   export IOS_P12=/path/to/dev-cert.p12
#   export IOS_P12_PASS=yourpassword
#   export IOS_PROVISION=/path/to/BYMRefitted.mobileprovision
#   ./ios/build-ios.sh
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IOS_DIR="$ROOT/ios"
DESCRIPTOR="$IOS_DIR/bym-refitted-ios.xml"
SWF_OUT="$ROOT/bin/bymr-ios.swf"
IPA_OUT="$IOS_DIR/BYM-Refitted.ipa"
TARGET="${IOS_TARGET:-ipa-test}"   # AOT: instantiates embedded symbol children + fonts like Android/desktop. interpreter (ipa-test-interpreter) leaves them null -> invisible UI. AOT packages in ~1min.

fail() { echo "❌ $*" >&2; exit 1; }

# --- preflight -------------------------------------------------------------
[ -n "${AIR_SDK_HOME:-}" ] || fail "Set AIR_SDK_HOME to your Harman AIR SDK root."
ADT="$AIR_SDK_HOME/bin/adt"
[ -x "$ADT" ] || fail "adt not found/executable at $ADT"
command -v asconfigc >/dev/null 2>&1 || fail "asconfigc not on PATH (npm i -g asconfigc)."

# --- 1. compile the SWF ----------------------------------------------------
# Default target is prod. BYMR_LOCAL=1 rewrites the SERVER_URL/CDN_URL defines to the
# Mac's LAN IP so the phone talks to `bun --watch src/server.ts` on :3001. localhost is
# NOT usable here — the phone would resolve it to itself. Override with BYMR_SERVER_URL.
PROJECT=asconfig.ios.json
if [ "${BYMR_LOCAL:-0}" = 1 ]; then
  SRV="${BYMR_SERVER_URL:-http://$(ipconfig getifaddr en0 || ipconfig getifaddr en1):3001/}"
  case "$SRV" in */) ;; *) SRV="$SRV/";; esac
  sed -E "s#https://server\.bymrefitted\.com/#${SRV}#; s#https://cdn\.bymrefitted\.com/#${SRV}#" \
    "$ROOT/asconfig.ios.json" > "$ROOT/asconfig.ios.gen.json"
  PROJECT=asconfig.ios.gen.json
  echo "▶ LOCAL mode — server: $SRV"
fi
echo "▶ Compiling game SWF via asconfigc…"
( cd "$ROOT" && asconfigc --sdk "$AIR_SDK_HOME" --project "$PROJECT" )
[ -f "$SWF_OUT" ] || fail "Expected $SWF_OUT after compile — not found."

# adt packages files relative to the descriptor's dir; stage the swf there.
cp "$SWF_OUT" "$IOS_DIR/bymr-ios.swf"

# --- 2. package the .ipa ---------------------------------------------------
[ -n "${IOS_P12:-}" ]       || fail "Set IOS_P12 (path to your .p12 dev cert)."
[ -n "${IOS_PROVISION:-}" ] || fail "Set IOS_PROVISION (path to .mobileprovision)."

# Notifications ANE (com.bym.notif): build once (cached) and stage for adt -extdir.
if [ ! -f "$IOS_DIR/ane/build/com.bym.notif.ane" ]; then
  echo "▶ Building notifications ANE (once)…"
  ( AIR_SDK_HOME="$AIR_SDK_HOME" bash "$IOS_DIR/ane/build-ane.sh" ) || fail "ANE build failed."
fi
mkdir -p "$IOS_DIR/ext" && cp -f "$IOS_DIR/ane/build/com.bym.notif.ane" "$IOS_DIR/ext/"

echo "▶ Packaging $TARGET → $IPA_OUT …"
( cd "$IOS_DIR" && "$ADT" -package \
    -target "$TARGET" \
    -provisioning-profile "$IOS_PROVISION" \
    -storetype pkcs12 -keystore "$IOS_P12" -storepass "${IOS_P12_PASS:-}" \
    "$(basename "$IPA_OUT")" \
    "$(basename "$DESCRIPTOR")" \
    -extdir ext \
    bymr-ios.swf \
    icons \
    notif.caf )

echo "✅ Built $IPA_OUT"
echo "   Next: install with Sideloadly/AltStore (free Apple ID). See ios/README.md."
